### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/pharo-ejdb#1] opened 2020-08-13 13:22 UTC
Hello,
I download Pharo with `curl https://get.pharo.org/64/80+vm | bash` and run the Metacello script from README. 
After install I have undeclared references to names such as: TFCalloutAPI, FFIMacLibraryFinder and TFWorker.
I suspect they are from https://github.com/pharo-project/threadedFFI-Plugin.
Is there are dependency declaration missing? or an advice on README on how to download a special Pharo?

**Comment by astares** [comment] 2023-09-16 15:33
I added CI builds today and it is loading just fine for Pharo 9, Pharo 10 and Pharo 11. See entry page of project.

<img width="169" alt="image" src="https://github.com/pharo-nosql/pharo-ejdb/assets/5980033/46b39cde-efbd-40ea-9284-fec4ecf8fd84">


@tinchodias Pharo 8 is rather outdated and the issue is from 2020 - we are now on Pharo 11 with a Pharo 12alpha. Can we close the issue?

**Comment by tinchodias** [comment] 2023-09-16 16:35
Thanks @astares !

**Closed as completed** 2023-09-16 16:34 UTC
Labels: question

**Comment by astares** [comment] 2023-09-17 07:07
@tinchodias Thanks for the feedback!
